ps2exe `
-inputFile ..\sources\launcher.ps1 `
-iconFile ..\assets\Rocketlaunch-Icon.ico `
-noConsole `
-noOutput `
-exitOnCancel `
-title "-Rocketlaunch!" `
-description "Start new projects, but very very quickly !" `
-company "By Stella, for Skrivanek GmbH" `
-product "Rocketlaunch!" `
-copyright "GNU GPL-3.0 Stella <stella.menier@gmx.de>" `
-version 2.0 `
-Verbose `
-outputFile ..\Rocketlaunch.exe